name: etc_sale_portal
description: "ETC SALE PORTAL WRAP"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_inappwebview: ^6.0.0
  permission_handler: ^11.3.1
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.14.1
  webview_flutter: ^4.8.0
  circular_menu: ^2.0.1

#flutter_inappwebview error in XCode 15 and 16 beta
#https://github.com/pichillilorenzo/flutter_inappwebview/issues/2221
dependency_overrides:
  flutter_inappwebview_ios:
    git:
      url: https://github.com/andychucs/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_ios

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: assets_constants.dart

#flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 24 # android min sdk min:16, default 21

#dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/splash.png
  # branding: assets/icons/splash.png
  # branding_bottom_padding: 24
  # color_dark: "#121212"
  # image_dark: assets/icons/splash.png
  # branding_dark: assets/icons/splash.png

  android_12:
    image: assets/icons/splash_12.png
    icon_background_color: "#ffffff"

  web: false

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
