///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String iconsAppIcon = 'assets/icons/app_icon.png';
  static const String iconsSplash = 'assets/icons/splash.png';
  static const String iconsSplash12 = 'assets/icons/splash_12.png';

}
